#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS_PATH = ROOT / "contracts.json"
OUTPUT_PATH = ROOT / "Orda Control" / "Core" / "Networking" / "GeneratedContracts.swift"
DTO_OUTPUT_PATH = ROOT / "Orda Control" / "Models" / "GeneratedContractDTOs.swift"


def swift_case_name(path: str) -> str:
    chunks = [c for c in path.strip("/").split("/") if c]
    name = "_".join(chunks).replace("-", "_")
    return name


# Paths used by the iOS app but not (yet) listed in contracts.json — keep in sync with Swift call sites.
EXTRA_ENDPOINT_PATHS: tuple[str, ...] = (
    "/api/admin/birthdays",
    "/api/admin/cashflow",
    "/api/admin/expense-categories",
    "/api/admin/client/bookings",
    "/api/admin/client/support",
    "/api/admin/customers",
    "/api/admin/customers/history",
    "/api/admin/expense-templates",
    "/api/admin/kpi-dashboard",
    "/api/admin/operator-analytics",
    "/api/admin/operators",
    "/api/admin/operators/profile",
    "/api/admin/point-devices",
    "/api/admin/profitability",
    "/api/admin/ratings",
    "/api/admin/reports/monthly",
    "/api/admin/salary",
    "/api/admin/salary-rules",
    "/api/admin/shifts",
    "/api/admin/tasks",
    "/api/ai/assistant",
    "/api/ai/forecast",
    "/api/ai/weekly-report",
    "/api/analysis/ai",
    "/api/goals",
    "/api/point/arena",
    "/api/telegram/salary-snapshot",
    "/api/telegram/send",
    "/api/telegram/send-report",
    "/api/telegram/status",
)

# Swift enum case name when it must differ from swift_case_name(path) (legacy / shorter names).
CASE_NAME_BY_PATH: dict[str, str] = {
    "/api/admin/operator-analytics": "api_operator_analytics",
}


def case_name_for_path(path: str) -> str:
    return CASE_NAME_BY_PATH.get(path, swift_case_name(path))


def main() -> None:
    payload = json.loads(CONTRACTS_PATH.read_text(encoding="utf-8"))
    endpoints = payload.get("endpoints", [])

    seen_paths: set[str] = set()
    ordered_paths: list[str] = []
    for item in endpoints:
        p = item["path"]
        if p not in seen_paths:
            seen_paths.add(p)
            ordered_paths.append(p)
    for p in EXTRA_ENDPOINT_PATHS:
        if p not in seen_paths:
            seen_paths.add(p)
            ordered_paths.append(p)

    rows: list[tuple[str, str]] = []
    used_cases: set[str] = set()
    for path in ordered_paths:
        case = case_name_for_path(path)
        if case in used_cases:
            continue
        used_cases.add(case)
        rows.append((case, path))

    rows.sort(key=lambda r: r[0])

    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate_contracts_swift.py")
    lines.append("import Foundation")
    lines.append("")
    lines.append("enum ContractEndpoint: String, CaseIterable {")
    for case, path in rows:
        lines.append(f"    case {case} = \"{path}\"")
    lines.append("}")
    lines.append("")
    lines.append("extension ContractEndpoint {")
    lines.append("    var get: APIEndpoint { APIEndpoint(path: rawValue, method: .GET) }")
    lines.append("    var post: APIEndpoint { APIEndpoint(path: rawValue, method: .POST) }")
    lines.append("    var patch: APIEndpoint { APIEndpoint(path: rawValue, method: .PATCH) }")
    lines.append("}")
    lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    dto_template = """import Foundation

// AUTO-GENERATED baseline DTOs from contracts.json scan.
// Keep custom refinements in dedicated extension files.

"""
    DTO_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not DTO_OUTPUT_PATH.exists():
        DTO_OUTPUT_PATH.write_text(dto_template, encoding="utf-8")
    print(f"Generated: {OUTPUT_PATH}")
    print(f"Checked DTO file: {DTO_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
